---

- name: check for archive {{ snakeoil_domain }}_{{ current_date }}.tgz on ansible controller
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.stat:
    path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
  register: _certificate_archive_local

- name: define checksum for {{ snakeoil_domain }} on ansible controller
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.stat:
    path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
    get_checksum: false
    get_mime: false
    get_attributes: false
  register: _certificate_archive_checksum_local
  when:
    - _certificate_archive_local is defined
    - _certificate_archive_local.stat is defined
    - _certificate_archive_local.stat.exists | default('true')

- name: check for archive {{ snakeoil_domain }}_{{ current_date }}.tgz on destination
  ansible.builtin.stat:
    path: "{{ snakeoil_remote_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
  register: _certificate_archive_remote

- name: define checksum for {{ snakeoil_domain }} on destination
  ansible.builtin.stat:
    path: "{{ snakeoil_remote_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
    get_checksum: false
    get_mime: false
    get_attributes: false
  register: _certificate_archive_checksum_remote
  when:
    - _certificate_archive_remote is defined
    - _certificate_archive_remote.stat is defined
    - _certificate_archive_remote.stat.exists | default('true')

- name: set facts
  ansible.builtin.set_fact:
    snakeoil_certificate_archive_checksum_local: "{{ _certificate_archive_checksum_local.stat.checksum | default('+') }}"
    snakeoil_certificate_archive_checksum_remote: "{{ _certificate_archive_checksum_remote.stat.checksum | default('-') }}"

- name: transfer certificate to destination instance
  tags:
    - snakeoil
  when:
    - snakeoil_extract_to is defined and snakeoil_extract_to | length != 0
    - _certificate_archive_local.stat.exists | default('true') and
      not _certificate_archive_remote.stat.exists | default('false') or
      snakeoil_certificate_archive_checksum_local != snakeoil_certificate_archive_checksum_remote
  block:
    - name: propagate {{ snakeoil_domain }}_{{ current_date }}.tgz
      become: true
      ansible.builtin.copy:
        src: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
        dest: "{{ snakeoil_remote_tmp_directory }}/"
        mode: 0600

    - name: create {{ snakeoil_extract_to }}
      ansible.builtin.file:
        path: "{{ snakeoil_extract_to }}"
        state: directory
        mode: 0750

    - name: extract {{ snakeoil_domain }}_{{ current_date }}.tgz
      ansible.builtin.unarchive:
        src: "{{ snakeoil_remote_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
        dest: "{{ snakeoil_extract_to }}"
        remote_src: true

...
