---

snakeoil_force: false

snakeoil_extract_to: '/etc/ssl'

snakeoil_domain: bar.local
snakeoil_email: "cert@{{ snakeoil_domain }}"

snakeoil_life_time: 15

snakeoil_alt_names:
  - dns:
      - foo.bar.local
      - www.bar.local
  - ip:
      - 192.168.2.1

...
